In [234]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [235]:
df = pd.read_csv('../data/train.csv')

In [236]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [237]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    str
 4   Sex          891 non-null    str
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    str
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    str
 11  Embarked     889 non-null    str
dtypes: float64(2), int64(5), str(5)
memory usage: 83.7 KB

In [238]:
df.describe(include='all')

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
count,891.000000,891.000000,891.000000,891,891,714.000000,891.000000,891.000000,891,891.000000,204,889
unique,NaN,NaN,NaN,891,2,NaN,NaN,NaN,681,NaN,147,3
top,NaN,NaN,NaN,"Braund, Mr. Owen Harris",male,NaN,NaN,NaN,347082,NaN,G6,S
freq,NaN,NaN,NaN,1,577,NaN,NaN,NaN,7,NaN,4,644
mean,446.000000,0.383838,2.308642,NaN,NaN,29.699118,0.523008,0.381594,NaN,32.204208,NaN,NaN
std,257.353842,0.486592,0.836071,NaN,NaN,14.526497,1.102743,0.806057,NaN,49.693429,NaN,NaN
min,1.000000,0.000000,1.000000,NaN,NaN,0.420000,0.000000,0.000000,NaN,0.000000,NaN,NaN
25%,223.500000,0.000000,2.000000,NaN,NaN,20.125000,0.000000,0.000000,NaN,7.910400,NaN,NaN
50%,446.000000,0.000000,3.000000,NaN,NaN,28.000000,0.000000,0.000000,NaN,14.454200,NaN,NaN
75%,668.500000,1.000000,3.000000,NaN,NaN,38.000000,1.000000,0.000000,NaN,31.000000,NaN,NaN
max,891.000000,1.000000,3.000000,NaN,NaN,80.000000,8.000000,6.000000,NaN,512.329200,NaN,NaN

In [239]:
df.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [240]:
tab = pd.crosstab(df['Pclass'], df['Survived'])

print(tab)

Survived    0    1
Pclass
1          80  136
2          97   87
3         372  119

In [241]:
for pclass, line in tab.iterrows():

    not_survived = line[0]
    survived = line[1]

    print(f"Survival rate for class {pclass}: {100*survived/(survived+not_survived):.2f}%")

# The higher the class, the higher the survival rate

Survival rate for class 1: 62.96%
Survival rate for class 2: 47.28%
Survival rate for class 3: 24.24%

In [242]:
tab = pd.crosstab(df['Sex'], df['Survived'])

print(tab)

Survived    0    1
Sex
female     81  233
male      468  109

In [243]:
for Sex, line in tab.iterrows():

    not_survived = line[0]
    survived = line[1]

    print(f"Survival rate for {Sex}: {100*survived/(survived+not_survived):.2f}%")

# Female has higher survival rate (they tried to save more womans and girls)

Survival rate for female: 74.20%
Survival rate for male: 18.89%

In [244]:
conditions = [
    (df['Age'] < 12),
    (df['Age'] >= 12) & (df['Age'] < 18),
    (df['Age'] >= 18) & (df['Age'] < 60),
    (df['Age'] >= 60)
]

group = ['kid', 'teen', 'adult', 'elderly']

df['AgeGroup'] = np.select(conditions, group, default='unknown')

In [245]:
tab = pd.crosstab(df['AgeGroup'], df['Survived'])

print(tab)

Survived    0    1
AgeGroup
adult     353  222
elderly    19    7
kid        29   39
teen       23   22
unknown   125   52

In [246]:
for AgeGroup, line in tab.iterrows():

    not_survived = line[0]
    survived = line[1]

    print(f"Survival rate for age group {AgeGroup}: {100*survived/(survived+not_survived):.2f}%")

# The younger the age group, the higher the survival rate (they tried to save more kids and teens)

Survival rate for age group adult: 38.61%
Survival rate for age group elderly: 26.92%
Survival rate for age group kid: 57.35%
Survival rate for age group teen: 48.89%
Survival rate for age group unknown: 29.38%

In [247]:
print(df['Name'])

0                                Braund, Mr. Owen Harris
1      Cumings, Mrs. John Bradley (Florence Briggs Th...
2                                 Heikkinen, Miss. Laina
3           Futrelle, Mrs. Jacques Heath (Lily May Peel)
4                               Allen, Mr. William Henry
                             ...
886                                Montvila, Rev. Juozas
887                         Graham, Miss. Margaret Edith
888             Johnston, Miss. Catherine Helen "Carrie"
889                                Behr, Mr. Karl Howell
890                                  Dooley, Mr. Patrick
Name: Name, Length: 891, dtype: str

In [248]:
df['NameTitle'] = df['Name'].str.extract(r' ([A-Za-z]+)\.', expand=False)

In [249]:
df['NameTitle'].value_counts()

NameTitle
Mr          517
Miss        182
Mrs         125
Master       40
Dr            7
Rev           6
Major         2
Mlle          2
Col           2
Don           1
Mme           1
Ms            1
Lady          1
Sir           1
Capt          1
Countess      1
Jonkheer      1
Name: count, dtype: int64

In [250]:
mask = df['AgeGroup'] == 'unknown'

df.loc[mask, 'NameTitle'].value_counts()

# Mr = Adult
# Miss = Woman
# Mrs = Adult
# Master = Kid
# Dr = Probably adult, but maybe Elderly

NameTitle
Mr        119
Miss       36
Mrs        17
Master      4
Dr          1
Name: count, dtype: int64

In [251]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,AgeGroup,NameTitle
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,adult,Mr
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,adult,Mrs
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,adult,Miss
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,adult,Mrs
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S,adult,Mr

In [252]:
mask = df['Embarked'].isna()

df[mask]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,AgeGroup,NameTitle
61,62,1,1,"Icard, Miss. Amelie",female,38.0,0,0,113572,80.0,B28,NaN,adult,Miss
829,830,1,1,"Stone, Mrs. George Nelson (Martha Evelyn)",female,62.0,0,0,113572,80.0,B28,NaN,elderly,Mrs

In [253]:
print(df.groupby('Embarked')['Fare'].describe())

# For a 80.0 Fare, the Embarked value is probably C

          count       mean        std     min       25%    50%        75%  \
Embarked
C         168.0  59.954144  83.912994  4.0125  13.69795  29.70  78.500025
Q          77.0  13.276030  14.188047  6.7500   7.75000   7.75  15.500000
S         644.0  27.079812  35.887993  0.0000   8.05000  13.00  27.900000

               max
Embarked
C         512.3292
Q          90.0000
S         263.0000

In [254]:
df['Embarked'] = df['Embarked'].fillna('C')

In [255]:
TitleAge = {"Mr": "adult", "Mrs": "adult", "Dr": "adult", "Master": "kid"}

for title, age in TitleAge.items():

    mask = (df['AgeGroup'] == "unknown") & (df['NameTitle'] == title)

    df.loc[mask, 'AgeGroup'] = age

In [256]:
df['TicketCount'] = df.groupby('Ticket').transform('size')
df['IndividualFare'] = df['Fare']/df['TicketCount']

print(df.groupby('Pclass')['IndividualFare'].median())

Pclass
1    35.2500
2    13.0000
3     7.8542
Name: IndividualFare, dtype: float64

In [257]:
# Mapping "Miss" to AgeGroup categories

mask = (df['AgeGroup'] == "unknown") & (df['NameTitle'] == "Miss")

df[mask]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,AgeGroup,NameTitle,TicketCount,IndividualFare
28,29,1,3,"O'Dwyer, Miss. Ellen ""Nellie""",female,NaN,0,0,330959,7.8792,NaN,Q,unknown,Miss,1,7.879200
32,33,1,3,"Glynn, Miss. Mary Agatha",female,NaN,0,0,335677,7.7500,NaN,Q,unknown,Miss,1,7.750000
47,48,1,3,"O'Driscoll, Miss. Bridget",female,NaN,0,0,14311,7.7500,NaN,Q,unknown,Miss,1,7.750000
82,83,1,3,"McDermott, Miss. Brigdet Delia",female,NaN,0,0,330932,7.7875,NaN,Q,unknown,Miss,1,7.787500
109,110,1,3,"Moran, Miss. Bertha",female,NaN,1,0,371110,24.1500,NaN,Q,unknown,Miss,3,8.050000
128,129,1,3,"Peter, Miss. Anna",female,NaN,1,1,2668,22.3583,F E69,C,unknown,Miss,2,11.179150
180,181,0,3,"Sage, Miss. Constance Gladys",female,NaN,8,2,CA. 2343,69.5500,NaN,S,unknown,Miss,7,9.935714
198,199,1,3,"Madigan, Miss. Margaret ""Maggie""",female,NaN,0,0,370370,7.7500,NaN,Q,unknown,Miss,1,7.750000
229,230,0,3,"Lefebre, Miss. Mathilde",female,NaN,3,1,4133,25.4667,NaN,S,unknown,Miss,4,6.366675
235,236,0,3,"Harknett, Miss. Alice Phoebe",female,NaN,0,0,W./C. 6609,7.5500,NaN,S,unknown,Miss,1,7.550000
240,241,0,3,"Zabour, Miss. Thamine",female,NaN,1,0,2665,14.4542,NaN,C,unknown,Miss,2,7.227100
241,242,1,3,"Murphy, Miss. Katherine ""Kate""",female,NaN,1,0,367230,15.5000,NaN,Q,unknown,Miss,2,7.750000
264,265,0,3,"Henry, Miss. Delia",female,NaN,0,0,382649,7.7500,NaN,Q,unknown,Miss,1,7.750000
274,275,1,3,"Healy, Miss. Hanora ""Nora""",female,NaN,0,0,370375,7.7500,NaN,Q,unknown,Miss,1,7.750000
300,301,1,3,"Kelly, Miss. Anna Katherine ""Annie Kate""",female,NaN,0,0,9234,7.7500,NaN,Q,unknown,Miss,1,7.750000
303,304,1,2,"Keane, Miss. Nora A",female,NaN,0,0,226593,12.3500,E101,Q,unknown,Miss,1,12.350000
306,307,1,1,"Fleming, Miss. Margaret",female,NaN,0,0,17421,110.8833,NaN,C,unknown,Miss,4,27.720825
330,331,1,3,"McCoy, Miss. Agnes",female,NaN,2,0,367226,23.2500,NaN,Q,unknown,Miss,2,11.625000
358,359,1,3,"McGovern, Miss. Mary",female,NaN,0,0,330931,7.8792,NaN,Q,unknown,Miss,1,7.879200
359,360,1,3,"Mockler, Miss. Helen Mary ""Ellie""",female,NaN,0,0,330980,7.8792,NaN,Q,unknown,Miss,1,7.879200
368,369,1,3,"Jermyn, Miss. Annie",female,NaN,0,0,14313,7.7500,NaN,Q,unknown,Miss,1,7.750000
409,410,0,3,"Lefebre, Miss. Ida",female,NaN,3,1,4133,25.4667,NaN,S,unknown,Miss,4,6.366675
485,486,0,3,"Lefebre, Miss. Jeannie",female,NaN,3,1,4133,25.4667,NaN,S,unknown,Miss,4,6.366675
502,503,0,3,"O'Sullivan, Miss. Bridget Mary",female,NaN,0,0,330909,7.6292,NaN,Q,unknown,Miss,1,7.629200
564,565,0,3,"Meanwell, Miss. (Marion Ogden)",female,NaN,0,0,SOTON/O.Q. 392087,8.0500,NaN,S,unknown,Miss,1,8.050000
573,574,1,3,"Kelly, Miss. Mary",female,NaN,0,0,14312,7.7500,NaN,Q,unknown,Miss,1,7.750000
593,594,0,3,"Bourke, Miss. Mary",female,NaN,0,2,364848,7.7500,NaN,Q,unknown,Miss,1,7.750000
596,597,1,2,"Leitch, Miss. Jessie Wills",female,NaN,0,0,248727,33.0000,NaN,S,unknown,Miss,3,11.000000
612,613,1,3,"Murphy, Miss. Margaret Jane",female,NaN,1,0,367230,15.5000,NaN,Q,unknown,Miss,2,7.750000
653,654,1,3,"O'Leary, Miss. Hanora ""Norah""",female,NaN,0,0,330919,7.8292,NaN,Q,unknown,Miss,1,7.829200
680,681,0,3,"Peters, Miss. Katie",female,NaN,0,0,330935,8.1375,NaN,Q,unknown,Miss,1,8.137500
697,698,1,3,"Mullens, Miss. Katherine ""Katie""",female,NaN,0,0,35852,7.7333,NaN,Q,unknown,Miss,1,7.733300
727,728,1,3,"Mannion, Miss. Margareth",female,NaN,0,0,36866,7.7375,NaN,Q,unknown,Miss,1,7.737500
792,793,0,3,"Sage, Miss. Stella Anna",female,NaN,8,2,CA. 2343,69.5500,NaN,S,unknown,Miss,7,9.935714
863,864,0,3,"Sage, Miss. Dorothy Edith ""Dolly""",female,NaN,8,2,CA. 2343,69.5500,NaN,S,unknown,Miss,7,9.935714
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S,unknown,Miss,2,11.725000

In [ ]:
mask = (df['AgeGroup'] == "unknown") & (df['NameTitle'] == "Miss") & (df['TicketCount'] == 1)

df.loc[mask, 'AgeGroup'] = 'adult'

# Miss traveling alone is assumed to be an adult

In [263]:
mask = (df['AgeGroup'] == "unknown") & (df['NameTitle'] == "Miss") & (df['Parch'] == 0)

df.loc[mask, 'AgeGroup'] = 'adult'

In [264]:
mask = (df['AgeGroup'] == "unknown") & (df['NameTitle'] == "Miss")

df.loc[mask, 'AgeGroup'] = 'kid'

In [ ]:
PclassDeckLevel = {1: 3, 2: 2, 3: 1}

df['DeckLevel'] = df['Pclass'].map(PclassDeckLevel)